name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask gunicorn

    - name: Run tests
      run: echo "Add your test script here"

    - name: Deploy to EC2
      env:
        EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        ssh -i $EC2_KEY $EC2_USER@$EC2_PUBLIC_DNS "cd ~/flask_app && git pull origin main && sudo systemctl restart gunicorn"

    - name: Update S3 bucket
      run: aws s3 cp path/to/your/static/files s3://devops-assignment-[your_name] --recursive
